config/routes.rb
Rails.application.routes.draw do
  devise_for :users
resources :stories do
  resources :characters do
    resources :relationships, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :locations
  resources :histories
end
root "stories#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :story
  has_many :relationships
  has_many :related_characters, foreign_key: :second_character, class_name: 'Relationship'
end

app/models/history.rb
class History < ApplicationRecord
  belongs_to :story
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :story
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :first_character, class_name: 'Character'
  belongs_to :second_character, class_name: 'Character'

  def other_character (current_character)
    if self.first_character == current_character
      self.second_character
    else
      self.first_character
    end
  end
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :user
  has_many :characters
  has_many :locations
  has_many :histories
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :stories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
before_action :find_character, only: [:show, :edit, :update, :destroy]

  def index
    @story = Story.find(params[:story_id])
    @characters = Character.where(story_id: @story.id)
  end

  def new
  end

  def create
    @story = Story.find(params[:story_id])
    @character = @story.characters.create(character_params)
    @character.save

    redirect_to story_character_path(story_id: @story.id, id: @character.id)
  end

  def show
    @relationships = Relationship.where(first_character_id: @character.id).or(Relationship.where(second_character_id: @character.id))
  end

  def edit
  end

  def update
    @character.update_attributes(character_params)
    redirect_to story_character_path
  end

  def destroy
    @story = @character.story_id
		@character.destroy

		redirect_to story_characters_path
  end

  private
  def find_character
    @character = Character.find(params[:id])
  end

  def character_params
    params.require(:character).permit(:name, :gender, :age)
  end
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  before_action :find_history, only: [:show, :edit, :update, :destroy]

  def index
    @story = Story.find(params[:story_id])
    @histories = History.where(story_id: @story.id)
  end

  def new
  end

  def create
    @story = Story.find(params[:story_id])
    @history = @story.histories.create(location_params)
    @history.save

    redirect_to story_history_path(id: @history.id, story_id: @story.id)
  end

  def show
  end

  def edit
  end

  def update
    @history.update_attributes(location_params)
    redirect_to story_histories_path
  end

  def destroy
    @story = @history.story_id
    @history.destroy

    redirect_to story_histories_path
  end

  private

  def find_history
    @history = History.find(params[:id])
  end

  def location_params
    params.require(:history).permit(:title, :body)
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :find_location, only: [:show, :edit, :update, :destroy]

  def index
    @story = Story.find(params[:story_id])
    @locations = Location.where(story_id: @story.id)
  end

  def new
  end

  def create
    @story = Story.find(params[:story_id])
    @location = @story.locations.create(location_params)
    @location.save

    redirect_to edit_story_location_path(id: @location.id, story_id: @story.id)
  end

  def show
  end

  def edit
  end

  def update
    @location.update_attributes(location_params)
    redirect_to story_location_path
  end

  def destroy
    @story = @location.story_id
    @location.destroy

    redirect_to story_locations_path
  end

  private

  def find_location
    @location = Location.find(params[:id])
  end

  def location_params
    params.require(:location).permit(:name, :location_type, :population)
  end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :find_character, only: [:new, :show, :edit, :update, :destroy]
  before_action :find_relationship, only: [:edit, :update, :destroy]

  def new
    @characters = Character.where(story_id: @character.story_id).where.not(id: @character.id)
  end

  def create
    @story = Story.find(params[:story_id])
    @character = Character.find(params[:character_id])
    @relationship = Relationship.create(first_character_id: @character.id, second_character_id: params[:relationship][:second_character_id], description: params[:relationship][:description])
    if @relationship.save
      redirect_to story_character_path(story_id: @story.id, id: @character.id)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @relationship.update_attributes(relationship_params)
    redirect_to story_character_path(story_id: @character.story_id, id: @character.id)
  end

  def destroy
    @relationship = Relationship.find(params[:id])
    @relationship.destroy
    redirect_to story_character_path(story_id: @character.story_id, id: @character.id)
  end

  private
    def find_character
      @character = Character.find(params[:character_id])
    end

    def find_relationship
      @relationship = Relationship.find(params[:id])
    end

    def relationship_params
      params.require(:relationship).permit(:description, :first_character, :second_character)
    end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
before_action :find_story, only: [:show, :edit, :update, :destroy]

  def index
    @stories = Story.where(user_id: current_user.id)
  end

  def new
    @story = current_user.stories.build
  end

  def create
    @story = current_user.stories.build(story_params)

    if @story.save
      redirect_to @story
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    @story.update_attributes(story_params)
    redirect_to story_path
  end

  def destroy
    @story.destroy
    redirect_to stories_path
  end

  private
    def find_story
      @story = Story.find(params[:id])
    end

    def story_params
      params.require(:story).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/characters/edit.html.erb
<h1> Edit Character </h1>
<%= form_for @character, url: story_character_path do |f| %>
<p>
  <%= f.label :name %>
  <%= f.text_field :name, placeholder: @character.name %>
</p>
<p>
  <%= f.label :gender %>
  <%= f.text_field :gender, placeholder: @character.gender %>
</p>
<p>
  <%= f.label :age %>
  <%= f.text_field :age, placeholder: @character.age %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>

app/views/characters/index.html.erb
<h1> Character Index </h1>
<p>
  <% @characters.each do |c| %>
    <p>
    <%= link_to "#{c.name}", story_character_path(id: c.id, story_id: @story.id) %>
    </p>
  <% end %>
</p>

<br>

<p>
  <%= link_to 'New Character', new_story_character_path %>
<p>
  <%= link_to 'Back', story_path(id: @story.id) %>
</p>

app/views/characters/new.html.erb
<h1> New Character </h1>
<%= form_for :character, url: story_characters_path do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :gender %>
    <%= f.text_field :gender %>
  </p>
  <p>
    <%= f.label :age %>
    <%= f.text_field :age %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/characters/show.html.erb
<h1>
  <%= @character.name %>
</h1>
<p>
  Age: <%= @character.age %>
</p>
<p>
  Gender: <%= @character.gender %>
</p>
<p>
  <% @relationships.each do |r| %>
    <p>
      <%= r.other_character(@character).name %>
      <%= r.description %>
      <%= link_to "edit", edit_story_character_relationship_path(story_id: @character.story_id, character_id: r.first_character_id, id: r.id) %>
      <%= button_to "delete", story_character_relationship_path(story_id: @character.story_id, character_id: r.first_character_id, id: r.id), method: :delete %>
    </p>
  <% end %>
<p>
  <%= link_to "New Relationship", new_story_character_relationship_path(story_id: @character.story_id, character_id: @character.id) %>
</p>

<br>

<p>
  <%= link_to('Delete', story_character_path(story_id: @character.story_id, id: @character.id), method: :delete) %>
</p>
<p>
  <%= link_to 'Edit', edit_story_character_path(story_id: @character.story_id, id: @character.id) %>
</p>
<p>
  <%= link_to('Back', story_characters_path(story_id: @character.story_id)) %>
</p>

app/views/histories/edit.html.erb
<h1> Edit History </h1>
<%= form_for @history, url: story_history_path do |f| %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %>
    <%= f.text_area :body, placeholder: @history.body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/histories/index.html.erb
<h1> History Index </h1>
<p>
  <% @histories.each do |h| %>
    <p>
    <%= link_to "#{h.title}", story_history_path(id: h.id, story_id: @story.id) %>
    </p>
  <% end %>
</p>

<br>

<p>
  <%= link_to 'New History', new_story_history_path %>
<p>
  <%= link_to 'Back', story_path(id: @story.id) %>
</p>

app/views/histories/new.html.erb
<h1> New History </h1>
<%= form_for :history, url: story_histories_path do |f| %>
<p>
  <%= f.label :title %>
  <%= f.text_field :title %>
</p>
<p>
  <%= f.label :body %>
  <%= f.text_area :body %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>

app/views/histories/show.html.erb
<h1>
  <%= @history.title %>
</h1>

<p>
 <%= @history.body %>
</p>

<p>
  <%= link_to('Delete', story_history_path(story_id: @history.story_id, id: @history.id), method: :delete) %>
</p>
<p>
  <%= link_to 'Edit', edit_story_history_path(story_id: @history.story_id, id: @history.id) %>
</p>
<p>
  <%= link_to('Back', story_histories_path(story_id: @history.story_id)) %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StoryApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_include_tag 'application' %>
  </head>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <body>
    <%= yield %>
  </body>
</html>

app/views/locations/edit.html.erb
<h1> Edit Location </h1>
<%= form_for @location, url: story_location_path do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name, placeholder: @location.name %>
  </p>
  <p>
    <% if @location.location_type == "Planet" %>
      <%= f.label :population %>
      <%= f.text_field :population, placeholder: @location.population %>
    <% end %>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/locations/index.html.erb
<h1> Locations Index </h1>
<p>
  <% @locations.each do |l| %>
    <p>
    <%= link_to "#{l.name}", story_location_path(id: l.id, story_id: @story.id) %>
    </p>
  <% end %>
</p>

<br>

<p>
  <%= link_to 'New Location', new_story_location_path %>
<p>
  <%= link_to 'Back', story_path(id: @story.id) %>
</p>

app/views/locations/new.html.erb
<h1> New Location </h1>
<%= form_for :location, url: story_locations_path do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :type %>
    <%= f.text_field :location_type %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/locations/show.html.erb
<h1>
  <%= @location.name %>
</h1>

<p>
  <% if @location.location_type == "Planet" %>
    Population: <%= @location.population %>
  <% end %>
</p>

<p>
  <%= link_to('Delete', story_location_path(story_id: @location.story_id, id: @location.id), method: :delete) %>
</p>
<p>
  <%= link_to 'Edit', edit_story_location_path(story_id: @location.story_id, id: @location.id) %>
</p>
<p>
  <%= link_to('Back', story_locations_path(story_id: @location.story_id)) %>
</p>

app/views/relationships/edit.erb
<h1> Edit Relationship </h1>
<%= form_for @relationship, url: story_character_relationship_path do |f| %>
<p>
  <%= f.label :description %>
  <%= f.text_area :description %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>

app/views/relationships/new.erb
<h1> New Relationship </h1>
<%= form_for :relationship, url: story_character_relationships_path do |f| %>
<p>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <%= f.select :second_character_id, @characters.map {|c| [c.name, c.id]} %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>

app/views/stories/edit.html.erb
<h1> Edit Story </h1>
<%= form_for @story do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, placeholder: @story.title %>

  <%= f.submit %>
<% end %>

app/views/stories/index.html.erb
<h1> Story Index </h1>
<p>
  <% if user_signed_in? %>
    <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
  <% else %>
    <%= link_to 'Sign In', new_user_session_path %>
    <%= link_to 'Sign Up', new_user_registration_path %>
  <% end %>
</p>
<p>
  <% @stories.each do |s| %>
    <p>
    <%= link_to "#{s.title}", story_path(id: s.id) %>
    </p>
  <% end %>
</p>

<br>

<p>
  <%= link_to 'New Story', new_story_path %>
</p>

app/views/stories/new.html.erb
<h1> New Story </h1>
<%= form_for :story, url: stories_path do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.submit %>
<% end %>

app/views/stories/show.html.erb
<h1 class="title">
  <%= @story.title %>
</h1>
<p>
  <%= link_to 'Characters', story_characters_path(story_id: @story.id) %>
</p>

<p>
  <%= link_to 'Locations', story_locations_path(story_id: @story.id) %>
</p>

<p>
  <%= link_to 'History', story_histories_path(story_id: @story.id) %>
</p>

<br>
<p>
  <%= link_to 'Edit', edit_story_path(id: @story.id) %>
</p>
<p>
  <%= link_to('Delete', story_path(id: @story.id), method: :delete) %>
</p>
<p>
  <%= link_to 'Back', stories_path %>
</p>